Transform: AWS::Serverless-2016-10-31

Globals:
  # set of globals
  Function:
    Environment:
      Variables:
        # Change this to the bucket name of where you want to store your files
        INPUT_FILE_BUCKET: &INPUT_FILE_BUCKET incognito-input-files
        OUTPUT_FILE_BUCKET: &OUTPUT_FILE_BUCKET incognito-output-files

# Description:
#   # String

# Metadata:
#   # template metadata

# Parameters:
#   # set of parameters

# Mappings:
#   # set of mappings

# Conditions:
#   # set of conditions

Resources:
  # set of resources
  UploadDocumentFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Handler for spinning up a host site and invoking text processing lambda
      Handler: app.upload_handler
      CodeUri: uploadLambda/
      Runtime: python3.7
      Timeout: 30

  TextProcessFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Handler for text processing
      Handler: app.text_process_handler
      CodeUri: textProcessLambda/
      Runtime: python3.7
      Timeout: 60
      Policies:
        # Give function full S3 Access
        - AmazonS3FullAccess
        - AmazonTextractFullAccess
      Layers:
        - !Ref PopplerLayer
      Events:
        ApiCall:
          Type: Api
          Properties:
            RestApiId: !Ref TextProcessApi
            Path: /processText
            Method: put
        S3Upload:
          Type: S3
          Properties:
            Bucket: !Ref InputBucket
            Events: s3:ObjectCreated:Put
  
  PopplerLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes: [python3.6, python3.7, python3.8]
      ContentUri: poppler/package.zip
  
  TextProcessApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Name: Text Process
      BinaryMediaTypes:
        ['application/pdf', image/png, image/jpeg]

  InputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: *INPUT_FILE_BUCKET

  OutputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: *OUTPUT_FILE_BUCKET
      
# Outputs:
  # set of outputs