Transform: AWS::Serverless-2016-10-31

Globals:
  # set of globals
  Function:
    Environment:
      Variables:
        # Change this to the bucket name of where you want to store your files
        FILE_BUCKET_NAME: &FILE_BUCKET_NAME incognito-file-bucket-storage

# Description:
#   # String

# Metadata:
#   # template metadata

# Parameters:
#   # set of parameters

# Mappings:
#   # set of mappings

# Conditions:
#   # set of conditions

Resources:
  # set of resources
  TextProcessFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Handler for text processing
      Handler: app.text_process_handler
      CodeUri: src/
      Runtime: python3.8
      Events:
        S3Upload:
          Type: S3
          Properties:
            Bucket: !Ref FileStorageBucket
            Events: s3:ObjectCreated:*
        ApiCall:
          Type: Api
          Properties:
            Path: /processText
            Method: get
            
  
  UploadPdfApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Name: Upload PDF
      BinaryMediaTypes:
        ['application/pdf']
  
  UploadPdfFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Handler for uploading a pdf
      Handler: app.upload_handler
      CodeUri: src/
      Runtime: python3.8
      Events:
        UploadPdf:
          Type: Api
          Properties:
            RestApiId: !Ref UploadPdfApi
            Path: /uploadPdf
            Method: PUT
  
  FileStorageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: *FILE_BUCKET_NAME

# Outputs:
  # set of outputs